sculpin:
sculpin_theme:
    theme: sculpin/bootstrap-3-blog-theme
sculpin_content_types:

    posts:
        permalink: changelog/:year-:month-:filename/
        path: changelog
        enabled: true

    docs:
        type: path
        path: docs
        singular_name: doc
        enabled: true
        taxonomies:
            - category
            - tag
        permalink: pretty

    guides:
        type: path
        path: guides
        singular_name: guide
        enabled: true
        taxonomies:
            - category
            - authors
        permalink: pretty
