sculpin:
sculpin_theme:
    theme: sculpin/bootstrap-3-blog-theme
sculpin_content_types:

    posts:
        permalink: changelog/:year-:month-:filename/
        path: changelog
        enabled: true

    docs:
        type: path
        path: docs
        singular_name: doc
        enabled: true
        taxonomies:
            - category
            - tag
        permalink: pretty

    guides:
        type: path
        path: guides
        singular_name: guide
        enabled: true
        taxonomies:
            - category
            - authors
        permalink: pretty
    drupal:
        type: path
        path: docs/drupal
        enabled: true
        permalink: pretty
    eight:
        type: path
        path: docs/drupal/drupal8
        enabled: true
        permalink: pretty
    local:
        type: path
        path: docs/local
        enabled: true
        permalink: pretty
    organizations:
        type: path
        path: docs/organizations
        enabled: true
        permalink: pretty
    sites:
        type: path
        path: docs/sites
        enabled: true
        permalink: pretty
    backups:
        type: path
        path: docs/sites/backups
        enabled: true
        permalink: pretty
    code:
        type: path
        path: docs/sites/code
        enabled: true
        permalink: pretty
    create:
        type: path
        path: docs/sites/create
        enabled: true
        permalink: pretty
    database:
        type: path
        path: docs/sites/database
        enabled: true
        permalink: pretty
    domains:
        type: path
        path: docs/sites/domains
        enabled: true
        permalink: pretty
    files:
        type: path
        path: docs/sites/files
        enabled: true
        permalink: pretty
    logs:
        type: path
        path: docs/sites/logs
        enabled: true
        permalink: pretty
    migrate:
        type: path
        path: docs/sites/migrate
        enabled: true
        permalink: pretty
    newrelic:
        type: path
        path: docs/sites/newrelic
        enabled: true
        permalink: pretty
    security:
        type: path
        path: docs/sites/security
        enabled: true
        permalink: pretty
    settings:
        type: path
        path: docs/sites/settings
        enabled: true
        permalink: pretty
    varnish:
        type: path
        path: docs/sites/varnish
        enabled: true
        permalink: pretty
    users:
        type: path
        path: docs/users
        enabled: true
        permalink: pretty
    wordpress:
        type: path
        path: docs/wordpress
        enabled: true
        permalink: pretty
    wordpressnetworks:
        type: path
        path: docs/wordpress/site-networks
        enabled: true
        permalink: pretty
