sculpin:
sculpin_theme:
    theme: sculpin/bootstrap-3-blog-theme
sculpin_content_types:

    posts:
        permalink: changelog/:year-:month-:filename/
        path: changelog
        enabled: true

    docs:
        enabled: true
        singular_name: doc
        path: _doc
        taxonomies:
            - categories
            - tags
            - contributors
        permalink: docs/:slug_title/

    guides:
        layout: guide
        type: path
        path: _guide
        singular_name: guide
        enabled: true
        taxonomies:
            - categories
            - tags
            - contributors
        permalink: guides/:slug_title/
